package SumApp;


/**
* SumApp/SumOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sum.idl
* Sunday, May 16, 2021 7:49:16 PM IST
*/

public interface SumOperations 
{
  float sum (float a, float b);
} // interface SumOperations
