package SumApp;


/**
* SumApp/Sum.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sum.idl
* Sunday, May 16, 2021 7:49:16 PM IST
*/

public interface Sum extends SumOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sum
